* Abe's Oddysee

  The first game that kickstarted OWI, Abe's Oddysee almost completely
  held up despite it's age. Let's see where it excels and what minor
  annoyances I had:

** Graphics
   Arguably one of the strongest points of the game. Despite the fact
   that the game was created for relatively weak systems, its graphics
   is gorgeous and incredibly unique. The dark and threatening tone of
   the Industrial areas contrasts nicely with the untamed, beautiful
   Native wildlands.

   The characters all feel alive and move in a believable way. This is
   mostly because animations are realistically slow and have plenty of
   weight in them.
** Gameplay
   Oddworld brings the standard platform-based control scheme of the
   era, but with two very important twists. All areas are divided up
   into "grids" that make movement predictable and fair. Every time
   Abe takes a step, it's will be the same length. This makes stupid
   positioning based mistakes impossible.

   The other twist is of course the possession mechanic. While it
   isn't the only game which explored this concept, Abe's Oddysee is
   built around it and it gives enough agency to its players to use
   and abuse their enemies to the fullest. I have encountered multiple
   areas where the "intended" solution was to do something with the
   resources provided to you on that single screen, but instead of
   doing that I decided to check out the next screen where I realized
   the puzzle has yet another solution. Letting players do this make
   them feel smart without the game explicitly patting them on the
   head, which I think is the best way to subtly reward those who like
   creative solutions.
** Sound design
** Plot
