* So you want to learn about the Oddworld canon?

  An unsuspecting fan might expect that Oddworld ends where the game
  ends, which is already quite a lot of info, yet in reality there is
  so much more behind the scenes.

  On this page I'd like to collect all the places where you can find
  interviews, developer diaries and also sites covering the less known
  parts of Oddworld:

** Sites
   - [[https://oddworldlibrary.net][TOL]] :: 
        Xavier's Wiki of Oddworld. It's a well-monitored source of
	lore as only a select few members can edit it. Because of this,
	the site is relatively small, but should not be underestimated.
	Also this domain contains other projects like [[http://oddworldlibrary.net/archives/togg/][TOGG]] and [[https://oddworldlibrary.net/archives/web/][OWWW]] which
	are the largest resources of Oddworld images and archived
	Oddworld websites respectively.

   - [[https://oddworld.fandom.com][The Wikia]] :: The public Oddworld Wiki. It had a long history of\\
	being plagued by misinformation and fanon considered canon,\\
	however, in the recent years it has been taken over by a\\
	competent staff that almost completely renovated the site, making\\
	it a useful resource.

   - [[https://magogonthemarch.com][Magog on the March]] :: This site is less concerned with documenting
	things, it's real strength is archiving all kinds of obscure
	information that I have no idea how they can even find. The
	site's design might be a tad bit confusing at first, but believe
	me, if something ever mentioned Oddworld, you can almost be sure
	that M.o.M. has or will have it archived. Also time by time they
	release videos and essays about Oddworld's lore in a very
	beginner-friendly format.

   - [[https://oddworldforums.net][OWF]] :: While the forum has since fallen from grace a bit, the
	thread archivescontain valuable information from several (ex-)OWI
	members. Admittedly OWF is probably the hardest place to find
	info on, but it is there and with some spelunking one might just
	hit gold.

   - [[https://oddwords.hu][Oddwords]] :: My goal is to theorize and make the lore a bit more
	easily understandable to the common fan. Compared to the sites
	mentioned previously I don't have either the amount of material
	or the fame, but this doesn't stop me from trying.

** Recommended reading material
   This is obviously a subjective list, however, I believe every fan
   who considers themselves interested in the bigger picture should
   read at least some of these as they touch upon a few of the most
   important aspects of planet Oddworld:

   - [[https://magogonthemarch.com/nathan-interviews-lorne-lanning-again/][Nathan interviews Lorne Lanning again]] :: My personal favorite and
        pretty much the most important interview of them all. We get
        answers to things like the planets size and structure, a
        glimpse into the Industrialist world, how Mudokons worked
        before they were enslaved, etc...

   - [[https://magogonthemarch.com/2008-2/nathan-interviews-lorne-lanning/][Nathan interviews Lorne Lanning]] :: The previous part of the
        interview above has almost as many important details. Together
        they give you a good grasp about the situation going on.

   - [[https://magogonthemarch.com/oddworld-history/][Oddworld History]] :: The first events that sparked the conflict
        between Glukkons and Mudokons told in a kind of campfire
        story-like manner.

   - [[https://magogonthemarch.com/abes-exoddus-inhabitants/][Abe's Exoddus - Inhabitants]] :: While the page concerns itself
        mostly with the characters appearing in Exoddus, it provides
        enough info about them to earn a place on this list.

   - [[https://magogonthemarch.com/transcripts/egx-2017-lorne-lanning-interview/][EGX 2017 Caddicarus interview]] :: In this interview Lorne Lanning
        answered questions about the upcoming game, Soulstorm, Mudokon
        anatomy, the old Quintology and other Oddworld-related topics.

   - [[https://oddworldlibrary.net/wiki/Soulstorm_ARG_Summary][Soulstorm ARG Summary]] :: This one is a bit of an odd one out,
        because the content here was organized by Xavier and
        myself. It contains the story of the Soulstorm ARG in a
        condensed, but still detailed way.

   - Developer diaries:
     * [[https://oddworldlibrary.net/wiki/Abe%27s_Exoddus_Designer_Diaries_on_Videogames.com][Abe's Exoddus - Videogames.net]]
     * [[https://oddworldlibrary.net/wiki/Munch%27s_Oddysee_Designer_Diaries_on_Videogames.com][Munch's Oddysee - Videogames.net]]
     * [[https://oddworldlibrary.net/wiki/Munch%27s_Oddysee_Designer_Diaries_on_PlayNOW!/][Munch's Oddysee - PlayNOW!]]
   
   - [[https://magogonthemarch.com/qa/reddit-ama-2012/][Reddit AMA 2012]] :: A free-form Q&A where Stewart Gilray and Lorne
	Lanning answered some of the fans' questions, about their
	personal life, the games, what their future projects were and
	other topics.

   - The Art of Oddworld Inhabitants: The First Ten Years :: This book
        is a treasure trove, sadly quite literally. Because it was
        printed in such limited numbers, finding a reasonably priced
        copy isn't exactly easy, especially if you prefer hardcover
        books. Sadly for some reason the book was never reprinted, nor
        released as an e-book.

	However, a certain Russian fellow named слиг (that's "slig"
        written using the Cyrillic-alphabet) scanned in the book and
        published it on a few sites. While I can't share the links
        here for obvious reasons, I suggest looking around on the
        Internet Archive.

** Where to talk with others about the canon?
   Of course none of this mean much if you don't have anyone else to
   talk about the story. Here are a few communities where you can talk
   about the canon or anything else Oddworld related:

   - [[https://discord.gg/oddworld][Official Oddworld]] :: OWI's own Discord. Currently this community
        has the largest active fanbase and you can even chat with the
        developers here.

   - [[http://discord.gg/JGeyUMn][OWF's Discord]] :: The second largest Discord, started by a few OWF
        community members. The server has less rules and is because of
        this a lot more laid-back.

   - [[https://reddit.com/r/Oddworld][The Oddworld Reddit]] :: A relatively small Reddit community based
        around the game. While it isn't particularly active, it does
        have a very loyal core that comment under basically any kind
        of post.

   - [[https://oddworldforums.net][OWF]] :: Of course OWF is not only a lore source, but also a place
        where you can talk about the games. While the population of
        the site dropped considerably throughout the years, but it's
        still a very important community for discussing Oddworld.
